version: '3'
services:
    udp:
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/python_socket_server
        image: python_udp
        container_name: udp_server
        ports:
            - "10001:10001/udp"
            #  Host:Container/protocol
        command: python udp_server.py &
        restart: on-failure   
